# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eliminar_profesor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(690, 666)
        self.labelEliminarProf = QtWidgets.QLabel(Dialog)
        self.labelEliminarProf.setGeometry(QtCore.QRect(150, 50, 471, 221))
        font = QtGui.QFont()
        font.setFamily("Franchise")
        font.setPointSize(36)
        self.labelEliminarProf.setFont(font)
        self.labelEliminarProf.setObjectName("labelEliminarProf")
        self.inputID = QtWidgets.QLineEdit(Dialog)
        self.inputID.setGeometry(QtCore.QRect(330, 450, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.inputID.setFont(font)
        self.inputID.setText("")
        self.inputID.setObjectName("inputID")
        self.ID = QtWidgets.QLabel(Dialog)
        self.ID.setGeometry(QtCore.QRect(270, 450, 51, 51))
        font = QtGui.QFont()
        font.setFamily("High Jakarta")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.ID.setFont(font)
        self.ID.setObjectName("ID")
        self.btnVolver = QtWidgets.QPushButton(Dialog)
        self.btnVolver.setGeometry(QtCore.QRect(230, 560, 211, 51))
        font = QtGui.QFont()
        font.setFamily("High Jakarta")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btnVolver.setFont(font)
        self.btnVolver.setObjectName("btnVolver")
        self.btnEliminar = QtWidgets.QPushButton(Dialog)
        self.btnEliminar.setGeometry(QtCore.QRect(270, 510, 151, 31))
        font = QtGui.QFont()
        font.setFamily("High Jakarta")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btnEliminar.setFont(font)
        self.btnEliminar.setObjectName("btnEliminar")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(163, 196, 361, 231))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelEliminarProf.setText(_translate("Dialog", "Eliminar profesor"))
        self.ID.setText(_translate("Dialog", "ID:"))
        self.btnVolver.setText(_translate("Dialog", "volver"))
        self.btnEliminar.setText(_translate("Dialog", "eliminar"))
