# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 0, 361, 221))
        font = QtGui.QFont()
        font.setFamily("Franchise")
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnProfesores = QtWidgets.QPushButton(self.centralwidget)
        self.btnProfesores.setGeometry(QtCore.QRect(300, 150, 201, 51))
        font = QtGui.QFont()
        font.setFamily("High Jakarta")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnProfesores.setFont(font)
        self.btnProfesores.setObjectName("btnProfesores")
        self.btnAlumnos = QtWidgets.QPushButton(self.centralwidget)
        self.btnAlumnos.setGeometry(QtCore.QRect(300, 210, 201, 51))
        font = QtGui.QFont()
        font.setFamily("High Jakarta")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnAlumnos.setFont(font)
        self.btnAlumnos.setObjectName("btnAlumnos")
        self.btnMaterias = QtWidgets.QPushButton(self.centralwidget)
        self.btnMaterias.setGeometry(QtCore.QRect(300, 270, 201, 51))
        font = QtGui.QFont()
        font.setFamily("High Jakarta")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnMaterias.setFont(font)
        self.btnMaterias.setObjectName("btnMaterias")
        self.btnConsultarFaltas = QtWidgets.QPushButton(self.centralwidget)
        self.btnConsultarFaltas.setGeometry(QtCore.QRect(300, 330, 201, 51))
        font = QtGui.QFont()
        font.setFamily("High Jakarta")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnConsultarFaltas.setFont(font)
        self.btnConsultarFaltas.setObjectName("btnConsultarFaltas")
        self.btnRegistrarFalta = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegistrarFalta.setGeometry(QtCore.QRect(300, 390, 201, 51))
        font = QtGui.QFont()
        font.setFamily("High Jakarta")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnRegistrarFalta.setFont(font)
        self.btnRegistrarFalta.setObjectName("btnRegistrarFalta")
        self.btnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(340, 450, 121, 51))
        font = QtGui.QFont()
        font.setFamily("High Jakarta")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnSalir.setFont(font)
        self.btnSalir.setObjectName("btnSalir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ITES ACADEMICO"))
        self.btnProfesores.setText(_translate("MainWindow", "Profesores"))
        self.btnAlumnos.setText(_translate("MainWindow", "ALUMNOS"))
        self.btnMaterias.setText(_translate("MainWindow", "materias"))
        self.btnConsultarFaltas.setText(_translate("MainWindow", "consultar faltas"))
        self.btnRegistrarFalta.setText(_translate("MainWindow", "registrar falta"))
        self.btnSalir.setText(_translate("MainWindow", "SAlir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
